project:
  type: website
  output-dir: docs

website:
  title: "mlog"
  navbar:
    right:
      - about.qmd
      - icon: facebook
        href: https://www.facebook.com/matteo.pedani
      - icon: twitter
        href: https://twitter.com/matteopedani
      - icon: envelope
        href: mailto:grandtour.frascati@gmail.com
        aria-label: Email
format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual
lang: it

